### ISSUE TITLE
Mac OS support?

### ISSUE THREAD

**Issue by LeoMehraban** [ebkr/r2modmanPlus#766]
Hello
I've been trying out different methods to install TABS mods on Mac, and none of them have worked. However, there is a branch called "macOS-support", witch makes this seem the the most promising method, but I have not been able to get it to work. I'm new to this "issue" thing, but I've seen some people use it to ask for help. If anyone would know anything about the support for Mac, your help would be greatly appreciated.

Thanks.

**Comment by ebkr** [comment]
It's mostly working currently however is slightly outdated. There needs some work to bring it up to date again.

At the moment the branch can run MacOS native apps, however none of the uploads on TS support it and so it requires a bit more manual work which isn't feasible for a release until that's sorted.

**Comment by bo0tzz** [comment]
I tried running from the development branch on Mac. Everything went well until the point of launching the game - It seems like there might be a path hardcoded in the `macos_proxy`? 

```
boet@Boets-Air Peglin % ./macos_proxy "/Users/boet/Library/Application Support/Steam/steamapps/common/Peglin/peglin.app"
Unhandled exception. System.IO.DirectoryNotFoundException: Could not find a part of the path '/Users/cade/Documents/proxyout.txt'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.File.WriteAllText(String path, String contents)
   at ManagerProxy.Program.<>c__DisplayClass0_0.<Main>b__1(CliParams parameters)
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at ManagerProxy.Program.Main(String[] args)
zsh: abort      ./macos_proxy 
```

**Comment by HenrikPoulsen** [comment]
Is there an updated status for this?
I see there's some mac related code in the project, but there's no pkg or dmg in the releases, and no mention of it in the docs, so I guess it's not usable?

**Comment by 631068264** [comment]
Hello  anyone here ? Need support for mac

**Comment by BLOKBUSTR** [comment]
For now you can use either Crossover or Whisky. There are instructions for setting up r2modman in Whisky [in their docs](https://docs.getwhisky.app/game-support/r2modman.html). You may also want to browse through the rest of their docs to see how well certain games are supported.

**Comment by 631068264** [comment]
> For now you can use either Crossover or Whisky. There are instructions for setting up r2modman in Whisky [in their docs](https://docs.getwhisky.app/game-support/r2modman.html). You may also want to browse through the rest of their docs to see how well certain games are supported.
> 
> (Edit) I neglected the context of this issue, sorry. This method would only work with games built for Windows, as far as I'm aware. I suppose it'll be fine if the game you want to mod is available on Windows, but otherwise I don't have any ideas for how to mod a Mac game with a Windows-based manager.

@BLOKBUSTR Thanks for your inspiration , I find [How to Install r2modman on Mac with Crossover
](https://www.youtube.com/watch?v=Q_Nq-d5LX9g). I'm newbie , even don't know crossover can install exe.

**Comment by BLOKBUSTR** [comment]
If you're willing to pay after the free trial period, Crossover may be a good choice, but I've experienced some graphical issues with it like missing volumetrics. On the other hand, Whisky is free, although you won't have some features like Steam Overlay (which I hope they'll fix eventually).

Come to think of it, manual mod management is always an option too, especially if a dedicated mod manager isn't available on Mac, but it can get so tiresome when handling many mods or trying to match mods with friends for multiplayer... That's definitely where r2modman has saved me, so I look forward to seeing if/when Mac development will be picked back up.

**Comment by Dessix** [comment]
[Release v3.2.3](https://github.com/ebkr/r2modmanPlus/releases/tag/v3.2.3) works in crossover, as noted [in the Crossover compatibility docs](https://www.codeweavers.com/compatibility/crossover/r2modman#breakdown), but nothing past that point even launches. I vaguely suspect [this Quasar upgrade](https://github.com/ebkr/r2modmanPlus/pull/1823) may be responsible.

**Comment by TehBrian** [comment]
Can confirm @Dessix's observation. I'm on an M1 MacBook Pro. Launching the latest version (3.2.11) resulted in the error below. Downgrading to 3.2.3 fixed everything.

<img width="382" height="348" alt="Image" src="https://github.com/user-attachments/assets/9811fa08-e8b3-41b7-95e0-355d95b58d1c" />
